- name: "Ant | MacOSX | Is Installed?"
  ansible.builtin.command: "ant -version"
  register: ant_version_result
  changed_when: false
  failed_when: false
- name: "Ant | MacOSX | Install Ant"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - ant
  when: ant_version_result.rc != 0
