add_newline = false

[hostname]
ssh_only = false
format = "@[$hostname]($style) "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[status]
symbol = "💣 "
format = '[\[$symbol$status\]]($style) '
disabled = false

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-0"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[kubernetes]
disabled = false

[line_break]
disabled = false
