- name: "GnuPG | MacOSX | Is Installed?"
  ansible.builtin.command: "gpg --version"
  register: gpg_version_result
  changed_when: false
  failed_when: false
- name: "GnuPG | MacOSX | Install GnuPG"
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg
  when: gpg_version_result.rc != 0
