local colors = require("catppuccin.palettes").get_palette()
require("catppuccin").setup({
    flavour = "mocha",
    transparent_background = false,
    term_colors = false,
    dim_inactive = {
        enabled = true,
        shade = "dark",
        percentage = 0.15,
    },
    no_italic = false, -- Force no italic
    no_bold = false, -- Force no bold
    styles = {
        comments = { "italic" },
        keywords = { "bold" },
    },
    color_overrides = {
        mocha = {
            --            base = "#000000",
            --            mantle = "#000000",
            --            crust = "#000000",
            TelescopeBorder = { fg = colors.surface0, bg = colors.surface0 },
            TelescopePromptBorder = { fg = colors.surface0, bg = colors.surface0 },
            TelescopePromptNormal = { bg = colors.surface0 },
            TelescopePromptPrefix = { fg = colors.mauve, bg = colors.surface0 },
            TelescopePreviewTitle = { fg = colors.surface0, bg = colors.surface0 },
            TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
            TelescopeResultsTitle = { fg = colors.surface0, bg = colors.surface0 },
            TelescopeSelection = { bg = colors.surface1 },
            FloatBorder = { bg = colors.mantle, fg = colors.subtext1 },
            CmpDocBorder = { bg = colors.mantle, fg = colors.flamingo },
            StatusLine = { bg = colors.mantle },
            StatusLineNC = { bg = colors.mantle },
            WinBar = { bg = colors.base },
            WinBarNC = { bg = colors.base },
            VertSplit = { bg = colors.mantle },
            NvimTreeOpenedFile = { link = "TSTextReference" },
            IndentBlanklineContextChar = { fg = colors.surface2 },
            IndentBlanklineChar = { fg = colors.surface0 },
            NeotestPassed = { link = "healthSuccess" },
            NeotestSkipped = { link = "healthWarning" },
            NeotestFailed = { link = "healthError" },
            NeotestFocused = { link = "PMenuSel" },
            NeotestRunning = { link = "CursorLineNr" },
            NeotestBorder = { link = "Comment" },
            NeotestTest = { link = "Normal" },
            NeotestDir = { link = "Directory" },
            NeotestFile = { link = "Character" },
            NeotestIndent = { link = "Comment" },
            NeotestExpandMarker = { link = "Comment" },
            DiffAdd = { fg = "#A8FF60", bg = "#35522b" },
            DiffChange = { fg = "#E9C062", bg = "#8b733a" },
            DiffDelete = { fg = "#e87b94", bg = "#571727" },
            DiffText = { fg = "#F1FA8C", bg = "#8b733a" },
            DiffviewDiffAddAsDelete = { link = "DiffDelete" },
            HighlightedyankRegion = { bg = colors.surface1 },
        },
    },
    custom_highlights = {},
    integrations = {
        treesitter = true,
        native_lsp = {
            enabled = true,
            virtual_text = {
                errors = { "italic" },
                hints = { "italic" },
                warnings = { "italic" },
                information = { "italic" },
            },
            underlines = {
                errors = { "underline" },
                hints = { "underline" },
                warnings = { "underline" },
                information = { "underline" },
            },
        },
        coc_nvim = false,
        lsp_trouble = false,
        cmp = true,
        lsp_saga = false,
        gitgutter = true,
        gitsigns = true,
        telescope = true,
        nvimtree = {
            enabled = false,
            show_root = true,
            transparent_panel = false,
        },
        dap = {
            enabled = true,
            enable_ui = true, -- enable nvim-dap-ui
        },
        neotree = {
            enabled = true,
            show_root = true,
            transparent_panel = false,
        },
        which_key = true,
        indent_blankline = {
            enabled = true,
            colored_indent_levels = false,
        },
        dashboard = false,
        neogit = true,
        vim_sneak = false,
        fern = false,
        barbar = false,
        bufferline = false,
        markdown = true,
        lightspeed = false,
        ts_rainbow = false,
        hop = false,
        notify = true,
        telekasten = false,
        symbols_outline = true,
        mini = true,
        fidget = false,
    },
})

vim.cmd("colorscheme catppuccin")
