- name: "Check Rust"
  shell: "command -v cargo"
  register: cargo_exists
  ignore_errors: true
- name: Install rustup-init
  homebrew:
    name: rustup
    state: latest
- name: Install rustup
  command: rustup-init -y --no-modify-path
- name: Install nightly
  command: rustup toolchain install nightly
- name: Rust Update
  command: rustup update
