- name: "Rust | MacOSX | Check Rust"
  ansible.builtin.shell: "command -v cargo"
  register: cargo_exists
  changed_when: false
  failed_when: false
- name: "Rust | MacOSX | Install rustup"
  community.general.homebrew:
      name: rustup
      state: present
- name: "Rust | MacOSX | Install rust"
  ansible.builtin.command: rustup toolchain install stable
  when: cargo_exists.rc != 0
- name: "Rust | MacOSX | Install nightly"
  ansible.builtin.command: rustup toolchain install nightly
  when: cargo_exists.rc != 0
- name: "Rust | MacOSX | Rust Update"
  ansible.builtin.command: rustup update
  register: rustup_update
  changed_when: rustup_update.stdout is regex('updated - rustc')
