- name: "Rust | MacOSX | Check Rust"
  ansible.builtin.shell: "command -v cargo"
  register: cargo_exists
  changed_when: false
  failed_when: false
- name: "Rust | MacOSX | Install rustup-init"
  community.general.homebrew:
      name: rustup
      state: latest
- name: "Rust | MacOSX | Install rustup"
  ansible.builtin.command: rustup-init -y --no-modify-path
  when: cargo_exists.rc != 0
- name: "Rust | MacOSX | Install nightly"
  ansible.builtin.command: rustup toolchain install nightly
  when: cargo_exists.rc != 0
- name: "Rust | MacOSX | Rust Update"
  ansible.builtin.command: rustup update
  changed_when: true
