# Finder
show_all_files: true
ds_not_write_network_dev: true
ds_not_write_usb_dev: true
# Use list view in all Finder windows by default.
# Icon View:   "icnv"
# List View:   "Nlsv"
# Column View: "clmv"
# Cover Flow:  "Flwv"
finder_view_style: "Nlsv"
finder_path_bar: true
new_window_target: "PfHm"
new_window_target_path: "file://${HOME}"
create_desktop: false
full_posix_path: true
stage_manager: false
