- name: "Bartender | MacOSX | Check Install"
  ansible.builtin.stat:
    path: "/Applications/Bartender 6.app"
  register: bartender_install
- name: "Bartender | MacOSX | Install Bartender"
  community.general.homebrew_cask:
    name: bartender
    state: present
  when: not bartender_install.stat.exists
