- name: "Starship | MacOSX | Install Starship"
  community.general.homebrew:
    name: starship
    state: present
- name: "Starship | MacOSX | Link Conf"
  ansible.builtin.file:
    src: '{{ dots }}/starship/starship.toml'
    dest: '{{ home }}/.config/starship.toml'
    owner: '{{ user }}'
    group: '{{ group }}'
    state: link
