- name: "Tooling | MacOSX | Install"
  community.general.homebrew:
    name:
      - asdf
      - awk
      - bazelisk
      - buf
      - ccls
      - cmake-docs
      - commitlint
      - coreutils
      - direnv
      - drone-cli
      - editorconfig
      - eslint
      - eza
      - fd
      - ffmpeg
      - fontconfig
      - gcc
      - gnu-sed
      - gnu-tar
      - gnutls
      - grep
      - helix
      - htop
      - hub
      - hyperfine
      - llvm
      - lnav
      - ltex-ls
      - lz4
      - lzo
      - make
      - markdownlint-cli
      - mockery
      - mongocli
      - mongosh
      - mtr
      - ncurses
      - nmap
      - pkgconf
      - pre-commit
      - readline
      - ripgrep
      - ruff
      - rust-analyzer
      - shellcheck
      - snappy
      - sqlite
      - stylua
      - subversion
      - texinfo
      - tree
      - tree-sitter
      - vim
      - xz
      - yamllint
      - yarn
      - yq
      - zoxide
      - zstd
    state: present
- name: "Tooling | MacOSX | Add starpls tap"
  community.general.homebrew_tap:
    name: withered-magic/brew
    state: present
- name: "Tooling | MacOSX | Install starpls"
  community.general.homebrew:
    name: starpls
    state: present
