default_roles:
  - 1password
  # - aerospace
  - alfred
  - alt-tab
  - ant
  - arc
  - bartender
  - bat
  - container
  - chrome
  - compass
  - discord
  - dock
  - docker
  - fantastical
  - finder
  - fish
  - fonts
  - fzf
  - gh
  - ghostty
  - git
  - git-credential-manager
  - go
  # - gpg-suite
  - gnupg
  - helm
  - istats
  - iterm2
  #   - java
  - jetbrains
  - just
  - k8s
  - karabiner
  - keyboard
  - kitty
  - krew
  - kubectx
  - lazygit
  - little-snitch
  - lua
  - mas
  - menubar
  - muzzle
  - nim
  - nushell
  - nvim
  #   - npm
  #   - nvm
  - obsidian
  - podman
  - postman
  - python
  - raindropio
  - raycast
  - readdle-spark
  - ruby
  - rust
  - signal
  - spotify
  #   - ssh
  - starship
  - system
  - terraform
  - tldr
  - tmux
  - tooling
  - visual-studio-code
  - wezterm
  - zig
  - zsh
  - zed
go:
  packages:
    - package: mvdan.cc/gofumpt@latest
      cmd: gofumpt
    - package: golang.org/x/tools/cmd/goimports@latest
      cmd: goimports
