- name: "System | MacOSX | Update Homebrew"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
- name: "System | MacOSX | Install Homebrew Packages"
  community.general.homebrew:
    name:
      - jq
      - yamlfmt
    state: present
