- name: "Python Environment | MacOSX | Install Python Environment"
  community.general.homebrew:
    name:
      - pyenv
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present
- name: "Check Python 3.13.12 Installed"
  ansible.builtin.shell:
    cmd: pyenv versions | grep '3.13.12' | awk '{print $NF}'
  register: python_3_13_12_installed
  ignore_errors: true
- name: "Check Python 3.10.20 Installed"
  ansible.builtin.shell:
    cmd: pyenv versions | grep '3.10.20' | awk '{print $NF}'
  register: python_3_10_20_installed
  ignore_errors: true
- name: "Pyenv | Install 3.13 Python"
  ansible.builtin.shell:
    cmd: pyenv install 3.13.12
  when: not python_3_13_12_installed
- name: "Pyenv | Install 3.10 Python"
  ansible.builtin.shell:
    cmd: pyenv install 3.10.20
  when: not python_3_10_20_installed
- name: "Check Global"
  ansible.builtin.shell:
    cmd: pyenv global
  register: global_set
- name: "Set Global"
  ansible.builtin.shell:
    cmd: pyenv global 3.10.20
  when: global_set == "system" and global_set != 3.10.20
  ignore_errors: true
- name: "Install Pipx"
  ansible.builtin.pip:
    name: pipx
    state: present
    extra_args: --user
- name: "Ensure Path Pipx"
  ansible.builtin.command: python3 -m pipx ensurepath
- name: "Check Poetry"
  ansible.builtin.shell:
    cmd: poetry --version | grep "version" | awk '{print $NF}' | awk '{gsub(/[()]/, ""); print}'
  register: poetry_install
  ignore_errors: true
- name: "Install Poetry"
  ansible.builtin.shell:
    cmd: pipx install poetry==2.3.2
  when: not poetry_install
