- name: "Python Environment | MacOSX | Define Python Versions"
  ansible.builtin.set_fact:
    python_stable_version: "3.14.3"
    python_legacy_version: "3.10.20"

- name: "Python Environment | MacOSX | Install Build Dependencies"
  community.general.homebrew:
    name:
      - pyenv
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

- name: "Python Environment | MacOSX | Check Stable Python Installed"
  ansible.builtin.shell:
    cmd: "set -o pipefail && pyenv versions --bare | grep -E '^{{ python_stable_version }}$'"
    executable: /bin/bash
  register: python_stable_installed
  changed_when: false
  failed_when: false

- name: "Python Environment | MacOSX | Check Legacy Python Installed"
  ansible.builtin.shell:
    cmd: "set -o pipefail && pyenv versions --bare | grep -E '^{{ python_legacy_version }}$'"
    executable: /bin/bash
  register: python_legacy_installed
  changed_when: false
  failed_when: false

- name: "Python Environment | MacOSX | Install Stable Python"
  ansible.builtin.command:
    cmd: "pyenv install {{ python_stable_version }}"
  when: python_stable_installed.stdout == ""
  changed_when: true

- name: "Python Environment | MacOSX | Install Legacy Python"
  ansible.builtin.command:
    cmd: "pyenv install {{ python_legacy_version }}"
  when: python_legacy_installed.stdout == ""
  changed_when: true

- name: "Python Environment | MacOSX | Check Pyenv Global Version"
  ansible.builtin.command:
    cmd: pyenv global
  register: python_pyenv_global
  changed_when: false
  failed_when: false

- name: "Python Environment | MacOSX | Set Pyenv Global"
  ansible.builtin.command:
    cmd: "pyenv global {{ python_legacy_version }}"
  when: python_pyenv_global.stdout != python_legacy_version
  changed_when: true

- name: "Python Environment | MacOSX | Install Pipx"
  community.general.homebrew:
    name: pipx
    state: present

- name: "Python Environment | MacOSX | Check Poetry Version"
  ansible.builtin.shell:
    cmd: "set -o pipefail && poetry --version 2>/dev/null | awk '{print $NF}' | tr -d '()'"
    executable: /bin/bash
  register: python_poetry_version
  changed_when: false
  failed_when: false

- name: "Python Environment | MacOSX | Install Poetry"
  ansible.builtin.command:
    cmd: pipx install poetry==2.3.2
  when: python_poetry_version.stdout is not search("2.3.2")
  changed_when: true
