- name: "JetBrains | MacOSX | Install JetBrains Toolbox"
  community.general.homebrew_cask:
    name: jetbrains-toolbox
    state: present
- name: "Ideavimrc | Deploy Configuration"
  ansible.builtin.file:
    src: '{{ dots }}/intellij/.ideavimrc'
    dest: '{{ home }}/.ideavimrc'
    owner: '{{ user }}'
    group: '{{ group }}'
    state: link
