- name: "Aerospace | Install Aerospace"
  community.general.homebrew_cask:
    name: 'nikitabobko/tap/aerospace@0.12.0'
    state: present
    update_homebrew: true
- name: "Aerospace | Deploy Configuration"
  ansible.builtin.file:
    src: '{{ dots }}/aerospace'
    dest: '{{ home }}/.config/aerospace'
    owner: '{{ user }}'
    group: '{{ group }}'
    state: link
