- name: "Fonts | MacOSX | Install"
  community.general.homebrew_cask:
    name:
      - font-powerline-symbols
      - font-awesome-terminal-fonts
      - font-fira-code-nerd-font
      - font-fontawesome
      - font-inter
      - font-iosevka
      - font-jetbrains-mono
      - font-source-code-pro
    state: present
